/** @type {import('tailwindcss').Config} */
module.exports = {
        content: [
          "./index.html",
          "./src/**/*.{js,ts,jsx,tsx}",
        ],
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                "on-secondary-fixed": "#002019",
                "surface-container-highest": "#dbe4ed",
                "tertiary-fixed": "#ebe0da",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#c6c6c9",
                "surface-container-lowest": "#ffffff",
                "inverse-primary": "#c6c6c9",
                "surface-container-high": "#e0e9f2",
                "on-primary-fixed-variant": "#454749",
                "on-secondary-fixed-variant": "#005141",
                "on-error-container": "#93000a",
                "tertiary": "#645d58",
                "surface-bright": "#f6faff",
                "on-tertiary-fixed": "#1f1b17",
                "secondary": "#006b57",
                "surface": "#f6faff",
                "surface-dim": "#d2dbe4",
                "tertiary-container": "#f9eee7",
                "outline": "#75777a",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#cfc5be",
                "on-surface-variant": "#45474a",
                "error": "#ba1a1a",
                "surface-container": "#e6eff8",
                "on-primary": "#ffffff",
                "surface-tint": "#5d5e61",
                "on-tertiary": "#ffffff",
                "on-surface": "#141d23",
                "surface-variant": "#dbe4ed",
                "outline-variant": "#c5c6ca",
                "on-tertiary-container": "#736b66",
                "on-secondary-container": "#00705a",
                "surface-container-low": "#ecf5fe",
                "primary-fixed": "#e2e2e5",
                "on-background": "#141d23",
                "on-error": "#ffffff",
                "on-tertiary-fixed-variant": "#4c4641",
                "on-primary-fixed": "#1a1c1e",
                "on-primary-container": "#6b6d70",
                "inverse-surface": "#293138",
                "primary-container": "#f0f0f3",
                "secondary-fixed": "#15ffd1",
                "primary": "#5d5e61",
                "inverse-on-surface": "#e9f2fb",
                "secondary-fixed-dim": "#00e0b7",
                "secondary-container": "#00fccf",
                "background": "#f6faff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-desktop": "48px",
                "max-width": "1280px",
                "unit": "8px",
                "margin-mobile": "16px",
                "gutter": "24px",
                "section-y": "96px",
                "section-y-mobile": "56px"
            },
            "fontFamily": {
                "label-md": ["Anybody"],
                "headline-xl": ["Anybody"],
                "headline-lg": ["Anybody"],
                "headline-md": ["Anybody"],
                "headline-lg-mobile": ["Anybody"],
                "body-lg": ["Anybody"],
                "body-md": ["Anybody"],
                "label-sm": ["Anybody"],
                "display": ["Bebas Neue"],
                "ui": ["Montserrat"]
            },
            "fontSize": {
                "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
                "display-xl": ["64px", {"lineHeight": "1.05", "letterSpacing": "0.01em", "fontWeight": "400"}],
                "display-lg": ["40px", {"lineHeight": "1.1", "letterSpacing": "0.01em", "fontWeight": "400"}],
                "display-md": ["28px", {"lineHeight": "1.15", "letterSpacing": "0.01em", "fontWeight": "400"}]
            }
          },
        },
      };
